#!/bin/bash
set -e

# Install xcodegen if not available
if ! command -v xcodegen &> /dev/null; then
    brew install xcodegen
fi

# Generate Xcode project from project.yml
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

# Resolve SwiftPM dependencies — Xcode Cloud has automatic resolution
# disabled, and the xcodeproj (and its Package.resolved) is gitignored
# because it's regenerated by xcodegen on every build.
xcodebuild -resolvePackageDependencies \
    -project liiists.xcodeproj \
    -scheme liiists
