#!/bin/bash
set -e

# Install xcodegen if not available
if ! command -v xcodegen &> /dev/null; then
    brew install xcodegen
fi

# Generate Xcode project from project.yml
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

# Restore the committed SwiftPM lockfile into the regenerated xcodeproj.
# Xcode Cloud has automatic dependency resolution disabled, and the
# xcodeproj is gitignored (regenerated by xcodegen on every build), so
# Package.resolved must be carried in a committed path and copied into
# place after xcodegen runs. Update ci_scripts/Package.resolved when
# adding/upgrading SPM dependencies (regenerate via
# `xcodebuild -resolvePackageDependencies` locally).
SPM_DIR="liiists.xcodeproj/project.xcworkspace/xcshareddata/swiftpm"
mkdir -p "$SPM_DIR"
cp ci_scripts/Package.resolved "$SPM_DIR/Package.resolved"
